#
# Module manifest for module 'TenantReports'
#
# Generated by: Tom de Leeuw
#
# Generated on: 27/01/2026
#

@{
    # General module info
    RootModule           = 'TenantReports.psm1'
    Description          = 'PowerShell module for generating primarily Microsoft 365 reports. Analyzes tenant security posture across Conditional Access, Intune, Sentinel, Azure Security, and user/device compliance.'
    ModuleVersion        = '1.1.0'
    CompatiblePSEditions = @('Core')
    GUID                 = '47bcc344-5fe9-45e0-9da5-c7980b632535'
    PowerShellVersion    = '7.0'
    Author               = 'Tom de Leeuw'
    CompanyName          = 'SysTom'
    Copyright            = '(c) 2025 Tom de Leeuw. All rights reserved.'
    HelpInfoURI          = 'https://systom.dev'
    
    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules      = @(
        @{
            ModuleName    = 'ExchangeOnlineManagement'
            ModuleVersion = '3.9.0'
        }
        @{
            ModuleName    = 'Microsoft.Graph.Applications'
            ModuleVersion = '2.34.0'
        }
        @{
            ModuleName    = 'Microsoft.Graph.Authentication'
            ModuleVersion = '2.34.0'
        }
        @{
            ModuleName    = 'Microsoft.Graph.Beta.Security'
            ModuleVersion = '2.34.0'
        }
        @{
            ModuleName    = 'Microsoft.Graph.Beta.Users'
            ModuleVersion = '2.34.0'
        }
        @{
            ModuleName    = 'Microsoft.Graph.ChangeNotifications'
            ModuleVersion = '2.34.0'
        }
        @{
            ModuleName    = 'Microsoft.Graph.DeviceManagement'
            ModuleVersion = '2.34.0'
        }
        @{
            ModuleName    = 'Microsoft.Graph.Groups'
            ModuleVersion = '2.34.0'
        }
        @{
            ModuleName    = 'Microsoft.Graph.Identity.DirectoryManagement'
            ModuleVersion = '2.34.0'
        }
        @{
            ModuleName    = 'Microsoft.Graph.Identity.Governance'
            ModuleVersion = '2.34.0'
        }
        @{
            ModuleName    = 'Microsoft.Graph.Identity.SignIns'
            ModuleVersion = '2.34.0'
        }
        @{
            ModuleName    = 'Microsoft.Graph.Reports'
            ModuleVersion = '2.34.0'
        }
        @{
            ModuleName    = 'Microsoft.Graph.Security'
            ModuleVersion = '2.34.0'
        }
        @{
            ModuleName    = 'Microsoft.Graph.Users'
            ModuleVersion = '2.34.0'
        }
    )
    
    # Public functions/cmdlets/variables/aliases to export from this module
    FunctionsToExport    = @(
        # Orchestrator
        'Invoke-TntReport'
        
        # Individual reports
        'Get-TntAzureSecureScoreReport'
        'Get-TntConditionalAccessReport'
        'Get-TntDefenderEmailThreatReport'
        'Get-TntExchangeCalendarPermissionReport'
        'Get-TntExchangeMailboxPermissionReport'
        'Get-TntIntuneAppleCertificateReport'
        'Get-TntIntuneDeviceComplianceReport'
        'Get-TntM365AuditEvent'
        'Get-TntM365RiskyUserReport'
        'Get-TntM365SecureScoreReport'
        'Get-TntM365UserReport'
        'Get-TntPIMReport'
        'Get-TntPrivilegedRoleReport'
        'Get-TntDefenderIncidentReport'
        'Get-TntServicePrincipalPermissionReport'
        'Get-TntOrganizationReport'
        'Get-TntLicenseReport'
        'Get-TntConfigurationReport'
        'Get-TntLicenseChangeAuditReport'
        'Get-TntAppRegistrationExpiryReport'
        'Get-TntSharedMailboxComplianceReport'
        'Get-TntInboxForwardingRuleReport'
        
        # Utilities
        'Connect-TntGraphSession'
    )
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{
        PSData = @{
            LicenseUri               = 'https://github.com/systommy/TenantReports/blob/master/LICENSE'
            ProjectUri               = 'https://github.com/systommy/TenantReports'
            RequireLicenseAcceptance = $false
            ReleaseNotes             = ''
            Tags                     = @(
                'Microsoft365'
                'Security'
                'Reporting'
                'ConditionalAccess'
                'Intune'
                'SecureScore'
                'AzureAD'
                'EntraID'
                'Compliance'
                'MicrosoftGraph'
                'MSGraph'
                'Audit'
                'PIM'
                'Defender'
                'Sentinel'
                'Azure'
                'Exchange'
            )
        }
    }
}
